language: go

sudo: false
env:
  global:
    - secure: "PQOM57pSXhiJ+5o6OfurLcKLYL8eLvIm2gfIWzDyE/2LV7nMLXqEjjiEs4Cze4qP6yiB75TPy53ZgCs5lUvxfM7Oqd11LcxiHiBf23rfbwymU1QPokY7VExBNk+yZIgNfbCTdL6Vr24aBmIDe8pEMJC++X9PWdJDC2xEVvvCV4rC8TLCv9h4TTxR3iMlqGcWUzUHo1ksU6TgvPtLYUzI7CBCIYHOHvYGvW0bNuy5qGpvdzBo88+UMahasCLuSAfhaeerQf7sMHgpaN1zfUQNDMsnxBA1luy0EzTETaFdbxMZ1HF6D9Umg0xaM9k6vJwg+4WBj37lXGLKIcpclaldI1e7Ej7skKRRr35Pz8A9BK3zABax0gilePW+2OVPcdo8pSCYWW328sMkwWp3z4+tsgSiKg5oW8ruOyLG9ryRKiG9WCtmijIhl+oeJQDSzSbL/IHy8O3RkXVm5YJ2QfVi7lwAsQL9mvziav6YBBqroA8GrWRf+z++DL8E4eN2rlMXwT8LqH7kdfCsOq3gzt/+TdGUnr/hiCSlApq5DvBk05h2GnX3j3mlJtNcThyycUhwxRaLsA+k4GGIYHPMQkWMT6Hz8O4dkO59LlWWg4Jyz1WLNjYa7Uu6YZLTUo5dMF2IydfXhPboWXb+Mqy2Kobe7B+vE5SuR9PuCDT+WVQa/ko="

go:
  - 1.6.2
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go get -t ./...
  - go test -v -coverprofile=profile.cov github.com/andrewdruzhinin/go-anti-captcha/anticaptcha
  - goveralls -coverprofile=profile.cov

notifications:
  email: false
